create index.html file
st-xuyentran/FE-Internship-Summer-2022_Demo_FE-Exercise pull request #3
Opened 2022-06-08 09:28 UTC by st-xuyentran

### Description
- Complete task create home page 1

2022-06-08 14:10 UTC, st-trangnguyen requested changes
Bài làm của em còn thiếu:
- Div container
- Em add class vào cho tất cả thẻ, khi nào style mình dùng class thay vì thẻ, nếu sau này đổi thẻ chỉ cần đổi ở html, css ko cần đổi. nếu dùng thẻ để style lúc đổi mình phải đồi ở cả html và css file, như vậy ko tối ưu
- Em chưa định nghĩa đc grid system (row-col)
- Chưa define được các module có thể sử dụng ví dụ như btn.btn-primary, btn.btn-secondary hoặc badge,....
Tham khảo thêm bootstrap nhé

2022-06-08 14:10 UTC, st-trangnguyen commented on index.html
> +    <header class="nav-header">
Rank B:
- header class nên là `header` hoặc `page-header` 
- footer class nên là `footer` hoặc `page-footer` 
- main class nên là `main-content` hoặc `page-content`

2022-06-08 14:10 UTC, st-trangnguyen commented on index.html
> +      <ul class="nav-icon">
Rank B: nav-icon là gì ba? nhưng thứ trên menu thường sẽ có action hết nhé, thêm button hoặc a vào, đặt class lại hi

2022-06-08 14:10 UTC, st-trangnguyen commented on index.html
> +      <h2>Sale of the <span>summer</span> collection</h2>
Rank B: phần này em tách ra section banner

2022-06-08 14:10 UTC, st-trangnguyen commented on index.html
> +      <section class="">
Rank B: Phần này cũng sẽ thuộc banner như trên

2022-06-08 14:10 UTC, st-trangnguyen commented on index.html
> +            <button>View all</button>
Rank B: Thường những button có text như là more detail, view all này nọ thì sẽ chuyển sang page detail. Vậy em nên dùng thẻ a thay vì button

2022-06-09 08:41 UTC, st-vantran commented on index.html
> +            <div class="brand-contact">
Này dùng ul li nhé e

2022-06-09 08:41 UTC, st-vantran commented on index.html
> +        <form action="" class="form-user">
form section bên phải mà e, đâu phải nguyên footer đâu

2022-06-09 08:41 UTC, st-vantran commented on index.html
> +              <img src="" alt="" />
Thêm nội dung alt vào nhé, toàn bộ luôn

2022-06-09 08:41 UTC, st-vantran commented on index.html
> +            <li class="infor-products  col-3">
đặt tên class li lại nghen em, product-item

2022-06-09 08:41 UTC, st-vantran commented on index.html
> +      <section class="information">
Tên section nên là section-reason

2022-06-09 08:41 UTC, st-vantran commented on index.html
> +            <li class="infor-products  col-3">
đặt tên class li, product không s, nên là product-item

2022-06-09 08:41 UTC, st-vantran commented on index.html
> +      <section class="section-products">
duplicate classname section-products

2022-06-09 15:20 UTC, st-trangnguyen requested changes

2022-06-09 15:20 UTC, st-trangnguyen commented on index.html
> +            <a class="link-shop-now" href="#">
a rồi thì xóa button chỗ icon nghe em, click vào icon hay text để link đi nên bọc a ở ngoài hết là đc, remove thẻ div bọc ngoài a lun, ko cân thiết

2022-06-09 15:20 UTC, st-trangnguyen commented on index.html
> +                  <li class="category-item col-6">
Indent chỗ này bị sai em nhé, check lại format

2022-06-09 15:20 UTC, st-trangnguyen commented on index.html
> +          <div class="col-7">
Information list:

<ul.list-info>, <li.list-info-item> wrap 3 cụm thông tin.
Mỗi cụm thông tin gồm: <h5.list-title>, <ul.list-subinfo>, <li.list-item>, <a.list-item-link>

2022-06-09 15:20 UTC, st-trangnguyen commented on index.html
> +      <p class="bot-footer container">DESIGN BY ICEO.CO - © 2019. ALL RIGHTS RESERVED.</p>
```<p class="copyright txt-center">DESIGN BY ICEO.CO - © 2019. ALL RIGHTS RESERVED.</p>```

define dùng helper class txt-center để center text

2022-06-10 03:09 UTC, st-vantran commented on fashion-home-page.html
> +          <li class="nav-item-icon">
Mấy nút này 1 là chuyển qua trang 2 là làm hành động gì đó nên để a hoặc button nhé em. Ở đây nên để button

2022-06-10 03:09 UTC, st-vantran commented on fashion-home-page.html
> +            <li class="products-list col-3">
tên class = product-item.
Thường ở đây sẽ link tới trang sản phẩm nên em để thẻ a vào nhé

2022-06-10 07:03 UTC, st-vantran commented on fashion-home-page.html
> +                <li class="list-item">
đặt tên class ul li lại nghen em,  ex: options-list option-item ....
đừng đặt tên kiểu list-item?
Kiểm tra lại tên mấy thẻ ul li nhé

2022-06-10 07:03 UTC, st-vantran commented on fashion-home-page.html
> +              <p class="form-title" for="">
for ở thẻ p làm gì nhỉ

2022-06-10 07:18 UTC, st-vantran commented on fashion-home-page.html
> +      <section class="section-fomr">
sai chính tả

2022-06-10 07:18 UTC, st-vantran commented on fashion-home-page.html
> +                <li class="contac-item">
sai chính tả

2022-06-10 07:34 UTC, st-vantran commented on fashion-home-page.html
> +            <button class="btn btn-primary">Men</button>
Ở đây là thẻ a

2022-06-10 07:34 UTC, st-vantran commented on fashion-home-page.html
> +              <a href="#">
Thẻ a bọc hết luôn e

2022-06-10 07:34 UTC, st-vantran commented on fashion-home-page.html
> +            <li class="products-item col-3">
Bình thường list product thì link tới trang product đó nên em thêm thẻ a vào nhé

2022-06-10 07:49 UTC, st-vantran approved these changes
Looks good to me!

2022-06-10 08:09 UTC, st-trangnguyen approved these changes

2022-06-10 08:09 UTC, merged