Css Fashion page
st-xuyentran/FE-Internship-Summer-2022_Demo_FE-Exercise pull request #5
Opened 2022-06-12 13:12 UTC by st-xuyentran

### Description
Implement CSS fashion page

2022-06-13 17:29 UTC, st-vantran commented
Những phần này em đừng để absolute position, mà nên gom cụm lại set padding cho nguyên khối
![image](https://user-images.githubusercontent.com/79818439/173410544-560a91df-8ca8-45c4-8dac-0192d59df3bd.png)

![image](https://user-images.githubusercontent.com/79818439/173410638-c77560d7-90f6-42dc-91b5-6ecc34d7bbb8.png)

2022-06-13 17:44 UTC, st-trangnguyen requested changes
- Em bị lặp code nhiều quá
- Em nhìn lại design, đưa những cái css common như của ul, li, a,.. hoặc những module button, badge,..., container, row col... lên đầu trang. tiếp đó sẽ là css của page

2022-06-13 17:44 UTC, st-trangnguyen commented on fashion_styles/fashion_page.css
> +  width: 1440px;
gì mà width tùm lum lên ri

2022-06-13 17:44 UTC, st-trangnguyen commented on fashion_styles/fashion_page.css
> +  width: 1152px;
width gì đây, mấy cái này có container rồi

2022-06-13 17:44 UTC, st-trangnguyen commented on fashion_styles/fashion_page.css
> +.header-title {
header-title => header-logo

2022-06-13 17:44 UTC, st-trangnguyen commented on fashion_styles/fashion_page.css
> +  align-items: center;
gom nhóm flex lại

2022-06-13 17:44 UTC, st-trangnguyen commented on fashion_styles/fashion_page.css
> +  list-style: none;
`list-style: none;` tất cả ul li đều style none thì em phải style cho cả cái tag ul li
`text-decoration: none;` tất cả thẻ a đều như vậy nên lấy thẻ a style common lun

fix lại và remove hết đống lặp lại ni cho chị nghe

2022-06-13 17:44 UTC, st-trangnguyen commented on fashion-home-page.html
> +            <span class="banner-title-span">summer</span>
đặt class common `text-primary`
em phải đặt class sao sau này có những chỗ khác vẫn dùng ké đc

2022-06-13 17:44 UTC, st-trangnguyen commented on fashion-home-page.html
> +              <div class="btn-icon">
1 loại btn thôi. gì mà vừa secondary vừa icon

2022-06-13 17:44 UTC, st-trangnguyen commented on fashion_styles/fashion_page.css
> +.container {
css container chị có hướng dẫn ở đây
https://supremetechhq.slack.com/archives/C03JCADA1U3/p1655111184548319

2022-06-13 17:44 UTC, st-trangnguyen commented on fashion-home-page.html
> +                <div class="category-img group1"></div>
group1 là gì em? đặt tên class lại

2022-06-13 17:44 UTC, st-trangnguyen commented on fashion_styles/fashion_page.css
> +.badges {
em tạo 1 module dùng chung `badge`
.bagde => width, height, border radius, color,...
.badge .badge-danger => màu sắc background
.product-item .badge => position, vì ko phải badge nào cũng sẽ absolute

2022-06-14 10:20 UTC, st-trangnguyen reviewed
chị sẽ review tiếp ở bài tập sass nhé
về tìm hiểu nhiều hơn nha

2022-06-14 10:20 UTC, merged